# Development-specific overrides
services:
  app:
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    image: nearchrist-backend:dev

  postgres:
    ports:
      # Expose the database port to your host machine for easy access
      - "5432:5432"
