# Development-specific properties for the 'dev' profile
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nearchrist}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET_KEY:your_local_dev_secret_key_that_is_long_and_secure}
  expiration: 3600000 # 1 hour

server:
  port: 8080
