spring:
  # The 'prod' profile will be activated via an environment variable
  datasource:
    # NO defaults. These values MUST be provided by environment variables on the server.
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # Safest setting for production
      ddl-auto: validate
    # Hides SQL queries from production logs
    show-sql: false
  flyway:
    # Ensures database migrations run automatically on startup
    enabled: true
    locations: classpath:db/migration

jwt:
  # NO default secret. This MUST be provided by an environment variable.
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000 # 1 hour

server:
  port: 8080 # The internal port Nginx will proxy to
  # Essential for working behind the Nginx reverse proxy
  forward-headers-strategy: NATIVE